import{a as E,S as q,i as n}from"./assets/vendor-3bc7bad3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&i(m)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();const M="43050559-0509edef54e5bc117deb7e6a8",S="https://pixabay.com/api/";async function h(e,t,r){try{return(await E.get(S,{params:{key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r}})).data}catch(i){throw console.error("Error fetching images:",i),i}}const d=document.querySelector(".gallery");function y(e){if(e.length==0)n.error({message:"Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const t=e.map(r=>`<li class="photo-list-item">
        <a class="photos-list-link" href="${r.largeImageURL}">
        <img class="photo" src="${r.webformatURL}" alt="${r.tags}"/>
        </a>
        <ul class="container">
        <li class="item-container"><p><span class="accent">Likes</span></br>${r.likes}</p></li>
        <li class="item-container"><p><span class="accent">Views</span></br>${r.views}</p></li>
        <li class="item-container"><p><span class="accent">Comments</span></br>${r.comments}</p></li>
        <li class="item-container"><p><span class="accent">Downloads</span></br>${r.downloads}</p></li>
        </ul>
        </li>`).join("");d.insertAdjacentHTML("beforeend",t)}b.refresh()}const b=new q(".gallery a",{captionsData:"alt",captionDelay:250});b.refresh();function L(){n.error({title:"We're sorry, but you've reached the end of search results.",message,position:"topRight",backgroundColor:"lightblue"})}const R=document.querySelector(".form"),p=document.querySelector(".search-input"),w=document.querySelector(".loader"),u=document.querySelector(".load-more-btn");c();f();let l="",a=1;const g=15;R.addEventListener("submit",H);async function H(e){if(e.preventDefault(),l=p.value.trim(),a=1,d.innerHTML="",l===""){n.error({title:"Error",message:"Please fill in the field for search.",position:"topRight",color:"red"}),c();return}F(),v();try{const t=await h(l,a,g),r=t.totalHits;if(t.hits.length===0){d.innerHTML="",n.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red"}),c();return}else y(t.hits),p.value="",P();g*a>=r&&(c(),L())}catch(t){console.error("Error fetching images:",t),n.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"lightblue"})}finally{f()}}u.addEventListener("click",async()=>{try{u&&(a+=1);const e=await h(l,a,g),t=e.totalHits;y(e.hits),v(),g*a>=t&&(c(),L());const r=d.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}catch(e){n.error({title:"Error",message:`Error fetching more images: ${e}`,position:"topRight"})}finally{f()}});function v(){w.classList.remove("hidden")}function f(){w.classList.add("hidden")}function P(){u.style.display="block"}function c(){u.style.display="none"}function F(){const e=document.querySelector(".end-message");e&&e.remove()}
//# sourceMappingURL=commonHelpers.js.map
