import{i as a,S as m}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const d=document.querySelector("input");d.value.trim();function f(o){const i=`https://pixabay.com/api/?${new URLSearchParams({key:"43050559-0509edef54e5bc117deb7e6a8",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(i).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()})}const p=document.querySelector(".gallery");function h(o){if(o.length==0)a.error({message:"Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const s=o.map(r=>`<li class="photo-list-item">
        <a class="photos-list-link" href="${r.largeImageURL}">
        <img class="photo" src="${r.webformatURL}" alt="${r.tags}"/>
        </a>
        <ul class="container">
        <li class="item-container"><p><span class="accent">Likes</span></br>${r.likes}</p></li>
        <li class="item-container"><p><span class="accent">Views</span></br>${r.views}</p></li>
        <li class="item-container"><p><span class="accent">Comments</span></br>${r.comments}</p></li>
        <li class="item-container"><p><span class="accent">Downloads</span></br>${r.downloads}</p></li>
        </ul>
        </li>`).join("");p.insertAdjacentHTML("beforeend",s),new m(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}}const g=document.querySelector(".gallery"),y=document.querySelector("input"),c=document.querySelector("form"),l=document.querySelector(".loader");u();function L(){l.classList.remove("hidden")}function u(){l.classList.add("hidden")}c.addEventListener("submit",o=>{o.preventDefault();const s=y.value.trim();if(g.innerHTML="",s===""){a.error({color:"red",message:" Please fill in the field for search",position:"topRight"});return}L(),s&&f(s).then(i=>h(i.hits)).catch(i=>{a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})}).finally(()=>u()),c.reset()});
//# sourceMappingURL=commonHelpers.js.map
